# Generated by Django 5.0.6 on 2024-06-30 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelClass',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.BigIntegerField(default=1)),
                ('boolean_field', models.BooleanField(default=False)),
                ('date_field', models.DateField(default=datetime.datetime(2024, 6, 30, 23, 1, 31, 309446))),
                ('date_time_field', models.DateTimeField(default=datetime.datetime(2024, 6, 30, 23, 1, 31, 309445))),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('email_field', models.EmailField(default='', max_length=254)),
                ('float_field', models.FloatField(default=0)),
                ('file_field', models.FileField(default='', upload_to='ppp/')),
                ('time_field', models.TimeField()),
            ],
        ),
    ]
